app/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
import django.views.static

# admin
from django.contrib import admin
admin.autodiscover()
# Static files
urlpatterns = patterns('',
    (r'^feincms_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.FEINCMS_ADMIN_MEDIA_LOCATION, 'show_indexes': True}
    ),
    (r'^admin/filebrowser/', include('filebrowser.urls')),
)

# regular urls
urlpatterns += patterns('',
    url(r'^$', 'app.views.simplepage', name='homepage'),
    url(r'^admin/', include(admin.site.urls)),
  #  (r'^search/', include('haystack.urls')),
    url(r'^(?P<slug>[-\w]+)/$', 'app.views.simplepage', name='simplepage'),
)

# specific urls
urlpatterns += patterns('',
    url(r'^films-description/(\d+)/$', 'filmography.views.film_description', name='film_description'),
    url(r'^films-quotation/(\d+)/$', 'filmography.views.film_quotation', name='film_quotation'),
    url(r'^films/(?P<slug>[-\w]+)/$', 'filmography.views.film', name='film'),
    url(r'^contributors/(?P<slug>[-\w]+)/$', 'filmography.views.contributor', name='contributor'),
    url(r'^plays/(?P<slug>[-\w]+)/films/$', 'filmography.views.play_films', name='play_films'),
    url(r'^analysis/(?P<slug>[-\w]+)/$', 'filmography.views.analysis', name='analysis'),
)


# Preview errors in local
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^404$', handler404),
        (r'^500$', handler500),
        (r'^static_admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.ADMIN_MEDIA_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True})
    )

app/forms.py
#-*- coding:utf-8 -*-

from django.conf import settings
from django import forms
from django.core.mail import send_mail

class ContactForm(forms.Form):
    sender = forms.EmailField(max_length=100, required=True)
    subject = forms.CharField(max_length=100,  required=True)
    body = forms.CharField(widget=forms.widgets.Textarea, required=True)
    
    def send(self):
        recipient = settings.CONTACT_EMAIL
        if not isinstance(recipient, list) or not isinstance(recipient, tuple):
            recipient = (recipient,)
        send_mail(\
            self.cleaned_data['subject'],\
            self.cleaned_data['body'],\
            self.cleaned_data['sender'],\
            recipient\
        )

templates/partials/breadcrumb.html
<ul>
  <li class="home"><a href="{% url homepage %}">Home</a></li>
  {% for crumb in crumbs %}
  <li{% if forloop.last %} class="current"{% endif %}><a href="{{ crumb.url }}">{{ crumb.label }}</a></li>
  {% endfor %}
</ul>

templates/partials/contact_form.html
{% load_assets 'contact_form' %}

{% if message %}
  <p class="success">{{ message }}</p>
{% endif %}

<form method="post">
  {% csrf_token %}
  <ul>
    <li class="row">
      {{ form.sender.errors }}
      <label for="id_sender">Email *</label>
      {{ form.sender }}
    </li>
    <li class="row">
      {{ form.subject.errors }}
      <label for="id_subject">Sujet *</label>
      {{ form.subject }}
    </li>
    <li class="row">
      {{ form.body.errors }}
      <label for="id_body">Message *</label>
      {{ form.body }}
    </li>
  </ul>
  <input type="submit" class="submit" value="Envoyer" />
</form>

templates/partials/contributors.html
{% load_assets 'contributors' %}

<ul id="contributors">
{% for contributor in contributors %}
  <li>
    <a href="{% url contributor contributor.slug %}" title="View details of {{ contributor.fullname }}">
      <img src="{{ contributor.image }}" alt="{{ contributor.fullname }}" />
      <label>{{ contributor }}</label>
      <p>{{ contributor.company }}</p>
    </a>
  </li>
{% endfor %}
</ul>
<div class="clear"></div>

templates/partials/films.html
{% load_assets 'listing' %}

<ul class="listing">
{% for film in films %}
  <li>
    {% include '_film_row.html' %}
  </li>
{% endfor %}
</ul>

templates/partials/googlemaps.html
{% load_assets 'googlemaps' %}

<div id="map"></div>

templates/partials/play_adaptations.html
{% load_assets 'listing' %}

<dl>
{% for play in plays %}
{% if play.film_references.adaptations.all.0 %}
  <dt>{{ play }}</dt>
  <dd>
      <ul class="listing">
          {% for adaptation in play.film_references.adaptations.all %}
          <li>
              <a href="{% url film adaptation.film.slug %}">
                <label>{{ adaptation.film }}</label> - Dir. {{ adaptation.film.directors.all|join:', ' }} ({{ adaptation.film.release_date }})
              </a>
          </li>
          {% endfor %}
      </ul>
  </dd>
{% endif %}
{% endfor %}
</dl>

templates/partials/play_references.html
{% load_assets 'listing' %}

<dl>
{% for play in plays %}
{% if play.film_references.allusions.all.0 %}

  <dt>{{ play }}</dt>
  <dd>
      <ul class="listing">
          {% for reference in play.film_references.allusions.all %}
          <li>
              <a href="{% url film reference.film.slug %}">
                <label>{{ reference.film }}</label> - Dir. {{ reference.film.directors.all|join:', ' }} ({{ reference.film.release_date }})
              </a>
          </li>
          {% endfor %}
      </ul>
  </dd>
{% endif %}
{% endfor %}

templates/partials/plays.html
{% load_assets 'listing' %}

<ul class="listing">
{% for play in plays %}
  <li><a href="{% url play_films play.slug %}" title="See films related to {{play}}">{{ play }}</a></li>
{% endfor %}
</ul>

templates/partials/search.html
{% load_assets 'search_form' %}

<form method="get" id="search_form" action="{% link 'search_result' %}">
  {{ form }}
  <input type="submit" class="submit" value="search" />
</form>

templates/partials/search_result.html
<ul>
{% if films %}
    {% for film in films %}
        <li>{% include '_film_row.html' %}</li>
    {% endfor %}
{% else %}
    <p>No film found matching your query</p>
{% endif %}
</ul>